[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
dependencies = [
    "Jinja2",
    "EpisodeDL",
]

[project.optional-dependencies]
dev = ["black", "isort"]

[tool.isort]
profile = "black"
