[tool.poetry]
name = "kjaymiller"
version = "0.1.0"
description = ""
authors = ["kjaymiller <kjaymiller@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9.0,<4.0.0"
render-engine = "^2022.5.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
