name: Add Latest Post
# This workflow checks my blog for the latest posts
#

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v2

      - name: Install Feedparser
        run: python3 -m pip install feedparser

      - name: Update Readme
        run: python3 ./.github/actions/update_readme.py

      - name: load to github
        run: |
          git config user.name "Automated Publisher"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m ":robot: Automated update README: ${timestamp}" || exit 0
          git push
