name: Render Engine Run
# This workflow checks my blog for the latest posts
#

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Install Requirements
        run: |
          pip install pip-tools
          pip-compile --upgrade
          pip-sync

      - name: Generate new website
        env: 
            APP_SEARCH_ENDPOINT: ${{ secrets.APP_SEARCH_ENDPOINT}}
            APP_SEARCH_API_KEY: ${{ secrets.APP_SEARCH_API_KEY}}
            DIRECTORY: content
            APP_SEARCH_API_KEY= : ${{ secrets.IMAGEKIT_PUBLIC_KEY }}
        run: |
            python transistor.py $DIRECTORY
            python run.py

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true

      - name: Install and Run Tailwindcss
        run: |
          npm install
          npx tailwindcss build static/css/pre/tailwind.css -o static/css/tailwind.css

      - name: load to github
        run: |
          git config user.name "Automated Publisher"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git pull
          git commit -m ":robot: Automated New Blog Post: ${timestamp}" || exit 0
          git push
